### ISSUE TITLE
Bootloop after booting to fastboot

### ISSUE THREAD

**Issue by Vitaspiros** [HemanthJabalpuri/twrp_motorola_devon#3]
My device is running Lineage OS with microg 20 (Android 13)

After pressing Reboot > Reboot to Fastboot my device showed a blinking TWRP loading screen. I managed to fix it by flashing the LineageOS recovery again. It seems that the fastbootd TWRP mode doesn't work properly on the G32.

**Comment by HemanthJabalpuri** [comment]
Thanks for testing.

please try latest release and let me know.

**Comment by Vitaspiros** [comment]
Thank you for responding and trying to fix the issue.
I want to test it but I have one question before I do.

The previous TWRP recovery was flashed through Magisk. I put LineageOS recovery to fix the bootloop and flashed TWRP again through Magisk. Is it OK to flash TWRP as a Magisk Module on top of the previous TWRP?

Thank you in advance.

**Comment by HemanthJabalpuri** [comment]
Yes, it is fine to flash on top of existing TWRP.

**Comment by Vitaspiros** [comment]
Thank you for fixing this. 
Now it works as expected.

**Comment by HemanthJabalpuri** [comment]
Thanks for testing and taking time to open this  issue.
I don't have G32, so can't test things.
